# Workflow name displayed on the GitHub Actions tab
name: CI/CD Pipeline

# --- Triggers: Defines when this workflow runs ---
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# --- Concurrency: Prevents multiple runs for the same PR from overlapping ---
# If a new push is made to the PR, the previous workflow run is cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# --- Defaults: Define a default working directory for all run commands ---
# This saves us from repeating the path in every step.
defaults:
  run:
    working-directory: ./InvoLuckFrontend

# --- Jobs: The sequence of tasks to be executed ---
jobs:
  # --- 1. JOB: Linters ---
  linters:
    name: CI / Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Full Monorepo
        uses: actions/checkout@v4
        # We clone the full repo so that the "file:.." dependency works correctly.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'InvoLuckFrontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  # --- 2. JOB: Tests (Unit Tests with Jest) ---
  tests:
    name: CI / Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Full Monorepo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'InvoLuckFrontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

  # --- 3. JOB: System Tests (Type Checking) ---
  system-tests:
    name: CI / System Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Full Monorepo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'InvoLuckFrontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Check TypeScript Types
        run: npm run type-check

  # --- 4. JOB: Integration Tests (Playwright) ---
  integration-tests:
    name: CI / Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Full Monorepo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'InvoLuckFrontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Project for Playwright
        run: npm run build

      - name: Run Integration Tests (E2E)
        run: npm run test:e2e